#!/usr/bin/env python3
"""
Railway deployment setup script.
"""

def setup_railway():
    """Guide user through Railway deployment."""
    print("RAILWAY DEPLOYMENT SETUP")
    print("=" * 40)
    print()
    print("Railway is the easiest way to deploy your bot 24/7!")
    print()
    print("STEP-BY-STEP GUIDE:")
    print("-" * 20)
    print()
    print("1. CREATE RAILWAY ACCOUNT")
    print("   • Go to: https://railway.app")
    print("   • Sign up with GitHub (easiest)")
    print("   • Connect your GitHub account")
    print()
    print("2. START NEW PROJECT")
    print("   • Click 'New Project'")
    print("   • Select 'Deploy from GitHub repo'")
    print("   • Choose this repository")
    print()
    print("3. CONFIGURE ENVIRONMENT VARIABLES")
    print("   In Railway dashboard, go to Variables and add:")
    print()
    print("   Key: TELEGRAM_BOT_TOKEN")
    print("   Value: 8266854184:AAEvZqs0tbjctOeQsh3JGpYr84r272tbxd8")
    print()
    print("   Key: GOOGLE_WEB_APP_URL")
    print("   Value: https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec")
    print("   (Replace YOUR_SCRIPT_ID with your Google Apps Script ID)")
    print()
    print("   Key: LOG_LEVEL")
    print("   Value: INFO")
    print()
    print("4. DEPLOY")
    print("   • Railway will auto-detect Python")
    print("   • Click 'Deploy'")
    print("   • Wait for deployment (2-3 minutes)")
    print()
    print("5. GET YOUR WEBHOOK URL")
    print("   • After deployment, go to 'Settings' tab")
    print("   • Copy the 'Public URL' (something like: https://your-app.up.railway.app)")
    print()
    print("6. SET TELEGRAM WEBHOOK")
    print("   Run this command in your terminal:")
    print()
    print("   curl \"https://api.telegram.org/bot8266854184:AAEvZqs0tbjctOeQsh3JGpYr84r272tbxd8/setWebhook?url=https://your-app.up.railway.app/webhook\"")
    print()
    print("   (Replace the URL with your Railway URL)")
    print()
    print("DONE! Your bot now runs 24/7 on Railway!")
    print()
    print("TEST:")
    print("   Forward a message to @molavisale_bot")
    print("   Check your Google Sheet - data should appear instantly!")
    print()
    print("FREE TIER: Railway gives $5/month free credits")
    print("   Your bot will use very little resources")
    print()
    print("=" * 40)

if __name__ == '__main__':
    setup_railway()
